/* TEMPLATE FOR DOING USEFUL STUFF SAFELY */
BEGIN TRAN
BEGIN TRY
​
		​
		ALTER TABLE [AgentStudio].[dbo].[video_tutorials]
		ADD Type varchar(15) NOT NULL DEFAULT('Text Only');
		--Text Only
		--YouTube
		--Brightcove

		ALTER TABLE [AgentStudio].[dbo].[video_tutorials]
		ADD YouTubeLink varchar(2000) NULL;
​

		SELECT *
		FROM [AgentStudio].[dbo].[video_tutorials]
​
​
     /* LEAVE UNCOMMENTED UNTIL YOU ARE SURE THE USEFUL STUFF WORKS THEN -- AND ONLY THEN -- COMMENT IT OUT */
    	ROLLBACK TRAN
​
    /* UNCOMMENT ONLY WHEN YOU ARE SURE THE USEFUL STUFF WORKS */
		-- COMMIT TRAN
​
​
END TRY
BEGIN CATCH
    ROLLBACK TRAN
    /* WHEN AN ERROR OCCURS SHOULD TELL YOU WHERE IN THE USEFUL STUFF THE ERROR HAPPENED SOME DETAIL ABOUT WHY IT SOILED ITSELF */
    PRINT 'AT LINE: ' + CAST(ERROR_LINE() AS varchar(10));
    PRINT ERROR_MESSAGE();
END CATCH