/* TEMPLATE FOR DOING USEFUL STUFF SAFELY */
BEGIN TRAN
BEGIN TRY


    /* DO USEFUL STUFF HERE */

	SELECT TOP 100 *
	FROM AgentStudio.Billing.History h
	WHERE AppGUID = 'F8A2E1CA-4D16-E811-984C-001438BC341A' AND
	h.TxType != 'Billing Failure' AND
	h.TxType != 'Bill Correction' AND
	h.AuthOnly != 1 AND
	h.CreatedDate > DATEADD( d, -6, GETDATE() )  AND
	h.CreatedDate < DATEADD( d, 1, GETDATE() )
	;

	
	DELETE FROM AgentStudio.Billing.History
	WHERE AppGUID = 'F8A2E1CA-4D16-E811-984C-001438BC341A' AND
	TxGUID IN(
		'89DBB773-7116-E811-984C-001438BC341A',
		'560DCAA4-7116-E811-984C-001438BC341A'
	);

	SELECT TOP 100 *
	FROM AgentStudio.Billing.History h
	WHERE AppGUID = 'F8A2E1CA-4D16-E811-984C-001438BC341A' AND
	h.TxType != 'Billing Failure' AND
	h.TxType != 'Bill Correction' AND
	h.AuthOnly != 1 AND
	h.CreatedDate > DATEADD( d, -6, GETDATE() )  AND
	h.CreatedDate < DATEADD( d, 1, GETDATE() );


     /* LEAVE UNCOMMENTED UNTIL YOU ARE SURE THE USEFUL STUFF WORKS THEN -- AND ONLY THEN -- COMMENT IT OUT */
    	ROLLBACK TRAN

    /* UNCOMMENT ONLY WHEN YOU ARE SURE THE USEFUL STUFF WORKS */
    --	COMMIT TRAN


END TRY
BEGIN CATCH
    ROLLBACK TRAN
    /* WHEN AN ERROR OCCURS SHOULD TELL YOU WHERE IN THE USEFUL STUFF THE ERROR HAPPENED SOME DETAIL ABOUT WHY IT SOILED ITSELF */
    PRINT 'AT LINE: ' + CAST(ERROR_LINE() AS varchar(10));
    PRINT ERROR_MESSAGE();
END CATCH
