
/* TEMPLATE FOR DOING USEFUL STUFF SAFELY */
BEGIN TRAN
BEGIN TRY


    /* DO USEFUL STUFF HERE */

SELECT TOP 1000 [PageGUID]
      ,[ZoneGUID]
      ,[WebPartGUID]
      ,[SortOrder]
      ,[BlueprintGuid]
  FROM [AgentStudio].[dbo].[page_blueprint]
  WHERE PageGUID = 'C5C2BD1E-E042-D4B2-C7A6-EA87AE5DE01E';

	DELETE [AgentStudio].[dbo].[page_blueprint]
	WHERE PageGUID = 'C5C2BD1E-E042-D4B2-C7A6-EA87AE5DE01E'
	AND ZoneGUID = '332558B1-921B-2C41-111E-A4CBD051EBB8'
	AND WebPartGUID = '59321E2C-D44C-5BC2-6878-744C6B23D387'

SELECT TOP 1000 [PageGUID]
      ,[ZoneGUID]
      ,[WebPartGUID]
      ,[SortOrder]
      ,[BlueprintGuid]
  FROM [AgentStudio].[dbo].[page_blueprint]
  WHERE PageGUID = 'C5C2BD1E-E042-D4B2-C7A6-EA87AE5DE01E';


    /* LEAVE UNCOMMENTED UNTIL YOU ARE SURE THE USEFUL STUFF WORKS THEN -- AND ONLY THEN -- COMMENT IT OUT */
     ROLLBACK TRAN
        
    /* UNCOMMENT ONLY WHEN YOU ARE SURE THE USEFUL STUFF WORKS */
    -- COMMIT TRAN


END TRY
BEGIN CATCH     
    ROLLBACK TRAN
    /* WHEN AN ERROR OCCURS SHOULD TELL YOU WHERE IN THE USEFUL STUFF THE ERROR HAPPENED SOME DETAIL ABOUT WHY IT SOILED ITSELF */
    PRINT 'AT LINE: ' + CAST(ERROR_LINE() AS varchar(10));
    PRINT ERROR_MESSAGE();
END CATCH
