/* TEMPLATE FOR DOING USEFUL STUFF SAFELY */
BEGIN TRAN
BEGIN TRY

USE [AgentStudio]

    /* DO USEFUL STUFF HERE */

	/* Set the dev courses images */

	SELECT *
	FROM AgentStudio.Marketing.MiniCourses
	WHERE IsActive = 1;

	UPDATE AgentStudio.Marketing.MiniCourses
		SET EntityGuid	= 'E7F6E1E8-684A-4B7B-A332-9BA346DC5CCE',
		MediaGuid		= '9C993AAD-7339-40DE-BB4D-4D9CD5BCDE5B'
	WHERE Id = 3;

	UPDATE AgentStudio.Marketing.MiniCourses
		SET EntityGuid	= '6E332577-588E-4FD0-A779-97003CEE4ED8',
		MediaGuid		= '6F1CE102-8DEF-4FFB-A451-E79FE4DFF1BB'
	WHERE Id = 36;

	UPDATE AgentStudio.Marketing.MiniCourses
		SET EntityGuid	= 'A4662D5A-DD79-4266-B405-B69F5D81C8D5',
		MediaGuid		= '3F1D5A9E-77A1-46DD-BE1F-18C729F549DD'
	WHERE Id = 36;

	SELECT *
	FROM AgentStudio.Marketing.MiniCourses
	WHERE IsActive = 1;


     /* LEAVE UNCOMMENTED UNTIL YOU ARE SURE THE USEFUL STUFF WORKS THEN -- AND ONLY THEN -- COMMENT IT OUT */
    	ROLLBACK TRAN

    /* UNCOMMENT ONLY WHEN YOU ARE SURE THE USEFUL STUFF WORKS */
    	--COMMIT TRAN


END TRY
BEGIN CATCH
    ROLLBACK TRAN
    /* WHEN AN ERROR OCCURS SHOULD TELL YOU WHERE IN THE USEFUL STUFF THE ERROR HAPPENED SOME DETAIL ABOUT WHY IT SOILED ITSELF */
    PRINT 'AT LINE: ' + CAST(ERROR_LINE() AS varchar(10));
    PRINT ERROR_MESSAGE();
END CATCH
